### ISSUE TITLE
Aggregate schemas and models 

### ISSUE THREAD

**Issue by Jennifercheukyin** [software-students-fall2021/project-setup-sneaky-seven#98]
### Estimation of work
- 1

### Tasks: 

- [ ] all schemas needs to be compiled to Model and we’re exporting Model

- [ ] put all models under /backend/model folder

- [ ] when importing model into app.js , name it as upper case camel style, like AccessTokenModel
